### DISCUSSION TITLE
Unable to apply API config

### DISCUSSION THREAD

**Discussion by abhi1693** [cdalvaro/docker-salt-master#230] [Q&A] [answered]
I created a file named `api.conf` in the `config` directory with the following contents

```
netapi_enable_clients:
  - local
  - local_async
  - local_batch
  - local_subset
  - runner
  - runner_async
  - wheel
  - wheel_async
```

I then ran a curl command and received the following:

```
curl -k https://localhost:8000
{"return": "Welcome", "clients": ["local", "local_async", "local_batch", "local_subset", "runner", "runner_async", "ssh", "wheel", "wheel_async"]}
```

Notice the `ssh` inclusion in the result. How can I apply the custom config to my container?

**Comment by cdalvaro** [comment]
Hi @abhi1693 thank you for opening this discussion!

Could you tell me more about your salt instance? Your docker run command or docker-compose.yml file for example.

May be, the api tests can give you a hint: https://github.com/cdalvaro/docker-salt-master/blob/main/tests/salt-api/test.sh

**Reply by abhi1693** [reply]
I'm running a simple docker container in https://app.xapp.cloudmydc.com/ with the API service enabled. Here are environment varibles I have added to my container:

```
SALT_API_SERVICE_ENABLED=True
SALT_API_USER=saltapi
SALT_API_USER_PASS=saltpass
SALT_LOG_LEVEL=info
SALT_LEVEL_LOGFILE=warning
SALT_RESTART_MASTER_ON_CONFIG_CHANGE=True
```

**Reply by cdalvaro** [reply]
Is the `salt-api` port ~exposed~ published?

**Reply by abhi1693** [reply]
Yes, I'm also to access the API from the outside and have the same response

**Reply by cdalvaro** [reply]
Try simply getting an access token:

```
curl -sSk "https://localhost:8000/login" \
  -H "Accept: application/x-yaml" \
  -d username=saltapi \
  -d password=saltpass \
  -d eauth=pam
```

Does this command work?

This command should return something similar to this:

```
return:
- eauth: pam
  expire: 1709338221.8327441
  perms:
  - .*
  - '@jobs'
  - '@runner'
  - '@wheel'
  start: 1709295021.8327432
  token: ACCESS_TOKEN_HERE
  user: saltapi
```

**Reply by abhi1693** [reply]
I get this on the login endpoint

```
return:
- eauth: pam
  expire: 1709339376.252061
  perms:
  - .*
  start: 1709296176.2520607
  token: 2aa8f837dc87dbae81b8b222578bfe34824609f1
  user: saltapi
```

Is it normal for the unauthenticated endpoint to return a different payload?

**Reply by cdalvaro** [reply]
I'm not sure... Now that you have a token, you should authenticate your requests like this:

```
curl -sSk "https://localhost:8000" \
  -H "Accept: application/x-yaml" \
  -H "X-Auth-Token: ACCESS_TOKEN" \
  -d client=local -d tgt='*' -d fun=test.ping
return:
- minions list here
```

Take a look at this guide: https://salt-sproxy.readthedocs.io/en/latest/salt_api.html

May be your are missing this part in your salt-api.conf file:

```yaml
external_auth:
  pam:
    saltapi:
      - .*
      - '@runner'
      - '@wheel'
      - '@jobs'
```
