### ISSUE TITLE
_pygit2.GitError: Failed to authenticate SSH session: Unable to send userauth-publickey request

### ISSUE THREAD

**Issue by rhjensen79** [cdalvaro/docker-salt-master#106]
Hi.

Have you experienced this issue ? 

**Describe the bug**
When using Gitfs2 for remote git repo, i keep getting errors.
When doing it via cli, it works fine, and i can see, that it's using the same ssh key files.

**To Reproduce**
Create new github repo
Create ssh key, without password
put the keys in the keys folder, and name them accordingly
restart container, and watcht the logs.
test using cli to clone the repo, using ssh, and verify it works.

**Expected behavior**
No errors in logs, and able to access the gitfs repo

**Additional info**
The full log with the outputted error.

**Version report (please complete the following information):**
 - Host OS: Linux salt-statefulset-0 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Docker: K8S 1.20
 - Image tag: latest

**Additional context**

gitfs.conf
```
gitfs_provider: pygit2
gitfs_privkey: /home/salt/data/keys/gitfs_ssh
gitfs_pubkey: /home/salt/data/keys/gitfs_ssh.pub

gitfs_remotes:
  - git@github.com:rhjensen79/salt.git:
    - root: salt
    - base: master
```
<img width="1296" alt="Screenshot 2021-10-20 at 11 18 34" src="https://user-images.githubusercontent.com/24954205/138069281-55739153-a6d8-4d84-be0d-39ef43c9fe64.png">
