### ISSUE TITLE
Can't provide a single volume at /home/salt/data

### ISSUE THREAD

**Issue by mrichar1** [cdalvaro/docker-salt-master#264]
I am looking to run salt-master on a kubernetes cluster with a single persistent volume mounted in /home/salt/data to persist all the relevant salt-master config.

I have set this up as follows:

```
containers:
      - name: salt-master
        image: ghcr.io/cdalvaro/docker-salt-master:3007.1_2
        ports:
        - containerPort: 4505
        - containerPort: 4506
        volumeMounts:
        - name: salt-master-pv
          mountPath: /home/salt/data/
```

However the image expects separate volumes to be explicitly defined for `logs` and `keys` in the `Dockerfile`:

`VOLUME [ "${SALT_KEYS_DIR}", "${SALT_LOGS_DIR}" ]`

This causes these volumes to always be mounted - in my case since I am not specifying these volumes it remounts the local disk at these directories over the top of my mount:

```
# mount |grep salt
10.0.0.1:/volumes/salt-config on /home/salt/data type nfs (rw,relatime)
/dev/sda6 on /home/salt/data/keys type xfs (rw,noatime,attr2,inode64,logbufs=8,logbsize=32k,noquota)
/dev/sda6 on /home/salt/data/logs type xfs (rw,noatime,attr2,inode64,logbufs=8,logbsize=32k,noquota)
```

The fix for this is to omit the `VOLUMES` line in `Dockerfile` - this still allows volumes to be specified with docker on the command-line (e.g. `--volume $(pwd)/keys/:/home/salt/data/keys/`), but if not set then the container will just use /home/salt/data/keys 'as-is' - either the local disk, or whatever is mounted there. (Which is effectively identical to the current behaviour).

Would this be something you would consider changing?
